### ISSUE TITLE
Orders not displaying no zip money merchant account

### ISSUE THREAD

**Issue by datatechmedia** [zipMoney/magento2#21]
Hello,

I have installed this extension, it  was working fine, but suddenly I get one issue, one of my customer tried to pay with Zippay, and order placed successfully, I can see order in magento 2 admin also. But can't see same order in Zippay merchant account. This customer was paid as Guest. Then after I tried to place one more order to check for the issue as registered customer, my order also placed successfully and I can see my order in merchant account also.
Any one have any Idea about it? I also contacted ZipPay support about this, but still no reply from there.
Please help.

Thank You

**Comment by webgig** [comment]
@datatechmedia  Hi, Can you please contact us at integrations@zipmoney.com.au with the merchant details, possibly with the zipmoney logs from your server.
