### ISSUE TITLE
Magento 2.2.3 set mode from dev to prod error

### ISSUE THREAD

**Issue by htsupport** [zipMoney/magento2#28]
When setting mode from developer to production the compilation runs into this error.

  [ReflectionException]
  Class zipMoney\Api\ChargesApi does not exist

  [ReflectionException]
  Class zipMoney\Api\ChargesApi does not exist

**Comment by webgig** [comment]
@htsupport  Can you confirm that you have installed the extension properly. The extension  depends on our php client library ( https://github.com/zipMoney/merchantapi-php ).

**Comment by htsupport** [comment]
Thanks.. my mistake.. just downloaded and installed manually.. have installed via composer and all is well.
