### ISSUE TITLE
Can't checkout if product has no short_description

### ISSUE THREAD

**Issue by bachlee89** [zipMoney/magento2#29]
https://github.com/zipMoney/magento2/blob/534c9f8392c571d8d957fc6cf04484ea8ea7401f/Helper/Payload.php#L516

When we place an order that has a product without short_description, it will throw an exception:
`[2018-01-24 06:02:46] zipMoneyLog.DEBUG: Errors:- {"error":{"code":"request_invalid","message":"There are errors with the request, please see error items for more detail","details":[{"name":"order.items[0]","message":"The input of order.items[0] was not valid"},{"name":"order.items[2]","message":"The input of order.items[2] was not valid,The input of order.items[2] was not valid,The input of order.items[2] was not valid,The input of order.items[2] was not valid,The input of order.items[2] was not valid"},{"name":"order.items[0].description","message":"The input of order.items[0].description was not valid"}]}} [] []
[2018-01-24 06:02:46] zipMoneyLog.DEBUG: Errors:- 400 [] []
[2018-01-24 06:02:46] zipMoneyLog.DEBUG: Errors:- {} [] []
[2018-01-24 06:02:46] zipMoneyLog.DEBUG: An error occurred while to requesting the redirect url. [] []`

Please update this to make sure we can checkout even the product has no short_description

**Comment by webgig** [comment]
@bachlee89  We are working on the fix and should be out on the next release soon.
