### ISSUE TITLE
magento 1 migration

### ISSUE THREAD

**Issue by zainengineer** [zipMoney/magento2#31]
Zipmoney in magento 1 had following configuration

1. `payment/zipmoneypayment/public_key`
2. `payment/zipmoneypayment/key` 
3. `payment/zipmoneypayment/id`

But magento2 has only two configuration.

1. `payment/zipmoneypayment/merchant_private_key`
2. `payment/zipmoneypayment/merchant_public_key`

how can I map them ?

**Comment by webgig** [comment]
@zainengineer  The first configuration is from our old API and the second example is from our new API which we call the Merchant API. There is a new Magento 1 plugin for the new Merchant API  as well which uses the second example for the config. Please get in touch with our integrations  team (integrations@zipmoney.com.au) for more details.

**Comment by zainengineer** [comment]
thanks @webgig 

So I can't use keys from the old plugin in the new plugin?

**Comment by webgig** [comment]
@zainengineer  Correct. The v2 key is different. You can find your new keys in merchant dashboard.

**Comment by zainengineer** [comment]
thanks
