### ISSUE TITLE
Cannot use terms & conditions

### ISSUE THREAD

**Issue by srowlands** [zipMoney/magento2#32]
**Issue:**
When terms & conditions are enabled in checkout you cannot place an order. This seems related to existing issue (https://github.com/magento/magento2/issues/11885) and appears other custom payment methods suffer the same issue

**Workaround:**
The only workaround is to disable terms & conditions, or have them automatically apply (and reword to something like: "By placing this order I agree to terms and conditions"), which is not ideal.

### Testing environment:
1. **Magento version**:  Magento 2.2.3
2. **PHP version**: 7+
3. Fresh install of Magento with only ZipPay extension enabled & TOC enabled in checkout

**Comment by benzhangzip** [comment]
Hi @srowlands,

The terms and condition in checkout Magento2 has a few options, there is auto agree or manually checkbox agreed, currently only the manual agree did not work but I have a fix in our dev branch already, if you want to get this fix before release you could use that commit in here https://github.com/zipMoney/magento2/commit/05c81cf374cab95df3e1e501208504875fdaa698
This just affecting one JS file so easy to apply fix to your project.

Tested in default magento2 theme with default magento2 checkout not sure onestepcheckout as there are too many versions out there and we don't have them all for testing. Hope this helps.
