### ISSUE TITLE
Market place release

### ISSUE THREAD

**Issue by terrybakshi** [zipMoney/magento2#43]
Hi when will this be available in magento 2 market place

**Comment by benzhangzip** [comment]
Good question, but it is a question for Adobe Magento2, as using composer, basically you don't need Magento2 to put you in market place as you will not install it via FTP as it simply won't work without running command line, also they officially claim not support windows or mac (Magento2 docs said) could not see market place will work, maybe commercially Magento2 cloud, but they just want to take advantage of vendors.

**Comment by terrybakshi** [comment]
> Good question, but it is a question for Adobe Magento2, as using composer, basically you don't need Magento2 to put you in market place as you will not install it via FTP as it simply won't work without running command line, also they officially claim not support windows or mac (Magento2 docs said) could not see market place will work, maybe commercially Magento2 cloud, but they just want to take advantage of vendors.

I can understand that Adobe is been greedy in regards to this matter they are not even providing or not interested in providing support even for the issue they have in community version.
