### ISSUE TITLE
Unable to place order after i installed zipmoney extension

### ISSUE THREAD

**Issue by ajayjaiswalweb** [zipMoney/magento2#46]
Hi Support,

I installed this extension here:- http://new1.nufoot.com , I added product to cart when trying to checkout after clicking on "Place order" button loader is rotating only, not going to thanku page.

Please Help!

Thanks, Ajay

**Comment by davids123** [comment]
Hi Support,

I am also getting same no error is displaying in console.

**Comment by davids123** [comment]
Anyone will support for this module

**Comment by davids123** [comment]
If you are getting loading error then install PHP client library of this extension

https://github.com/zipMoney/merchantapi-php
