### ISSUE TITLE
PHP 7.1 and Composer

### ISSUE THREAD

**Issue by Lach1222** [zipMoney/magento2#52]
Hi, could you please updated the composer's required packages to support PHP 7.1 as [Magento 2.3 minimum PHP requirement is 7.1](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)

composer require zipmoney/magento2
Using version ^1.0 for zipmoney/magento2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zipmoney/magento2 1.0.1 requires php ~5.5.0|~5.6.0|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - zipmoney/magento2 1.0.0 requires php ~5.5.0|~5.6.0|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.1.25) does not satisfy that requirement.
    - Conclusion: don't install zipmoney/magento2 1.0.2|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.3|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.4|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.3|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.5|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.4|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.6|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.5|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.6|install magento/framework 100.1.16
    - zipmoney/magento2 1.0.2 requires magento/framework ^100.1.0|^101.0.0 -> satisfiable by magento/framework[100.1.0, 100.1.1, 100.1.2, 100.1.3, 100.1.4, 100.1.5, 100.1.6, 100.1.7, 100.1.8, 100.1.9, 101.0.0, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7].
    - magento/framework 101.0.1 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.2 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.3 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.4 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.5 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.6 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - magento/framework 101.0.7 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
    - Conclusion: don't install zipmoney/magento2 1.0.2|don't install colinmollenhour/php-redis-session-abstract v1.3.4|install magento/framework 101.0.0|install magento/framework 100.1.16
    - Conclusion: don't install zipmoney/magento2 1.0.2|don't install magento/framework 101.0.0|install magento/framework 100.1.16
    - Installation request for zipmoney/magento2 ^1.0 -> satisfiable by zipmoney/magento2[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].

**Comment by benzhangzip** [comment]
Hi @Lach1222 
We have push a fix version of 1.0.7 today which should fix the dependency issue for the new Magento2 versions, please try run composer require or update and let us know if the issue resolved thanks.
