### ISSUE TITLE
Unable to place an order when using rewards points

### ISSUE THREAD

**Issue by aligent-lturner** [zipMoney/magento2#54]
Magento 2 Commerce (Enterprise Edition) has a module for rewards points, which can be used to give a discount on the order.
When calling https://api.sandbox.zipmoney.com.au/merchant/v1/checkouts, an error is returned:

![image](https://user-images.githubusercontent.com/40189797/54661377-cf968000-4b29-11e9-8f7d-5a85632c3bb1.png)

I believe that details about the rewards point discount need to be sent with the request, so that the values can be validated properly.

**Comment by aligent-lturner** [comment]
I believe that `ZipMoney\ZipMoneyPayment\Helper\Payload` should be able to handle this in the same manner that discounts are currently applied (line 432).

**Comment by benzhangzip** [comment]
Hi @aligent-lturner 
Please upgrade to our latest version 1.0.10 which will fix this issue, as we had put in different way to balance out the cart total, without needs to know what promotion you used, as Enterprise and other third party extension might do very differently, and our way will fix once for all possible discount, thanks
