### ISSUE TITLE
Disable zip payment for international shipping (except AU and NZ)

### ISSUE THREAD

**Issue by SharpInstincts** [zipMoney/magento2#65]
Zip admin module doesn't seem to have any option to disable Zip payment option if shipping country is changed to non-AU non-NZ address. This should be either by default in code or should be there as an option in backend to disable this payment method. 

Right now we have to apply a custom solution to disable zip in this situation.

**Comment by benzhangzip** [comment]
Hi @SharpInstincts 
we are happy to inform you that we just release a new version 1.0.11 that fixing the country validation issues, please run composer update zipmoney/magento2 to get the latest version, and run the setup:di:compile in Magento2 console to refresh the code.
